version: '3.9'
services: 
    terraform:
        build:
            context: .
            dockerfile: terraform.Dockerfile
        volumes:
            - $PWD:/app
        working_dir: /app
    website:
        build: 
            context: .
        ports: 
           -  80:80
    selenium:
        image: selenium/standalone-chrome-debug
        ports:
            - 4444:4444
            - 5901:5900 #vnc server
    unit-tests:
        environment:
            SELENIUM_HOST: selenium
            SELENIUM_PORT: 4444
        volumes:
            - $PWD:/app
        build:
            context: .
            dockerfile: rspec.dockerfile
        entrypoint: rspec
        command: 
            - --pattern
            - /app/spec/unit/*_spec.rb