version: '3.9'
services: 
    jenkins:
        build: 
            context: .
            dockerfile: jenkins.Dockerfile
        volumes:
            - $PWD/jenkins_home:/var/jenkins_home
            - $PWD:/app
        ports:
            - 8080:8080
    aws:
        image: organs/awscli
        environment: 
            AWS_ACCESS_KEY_ID: ${AWS_A_K_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_S_A_K}
            AWS_REGION: us-west-2
            AWS_DEFAULT_REGION: us-west-2
        volumes:
            - $PWD:/app
        working_dir: /app
    terraform:
        build:
            context: .
            dockerfile: terraform.Dockerfile
        environment: 
            AWS_ACCESS_KEY_ID: ${AWS_A_K_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_S_A_K}
            AWS_REGION: us-west-2
            AWS_DEFAULT_REGION: us-west-2
        volumes:
            - $PWD:/app
        working_dir: /app
    website:
        build: 
            context: .
        ports: 
           -  80:80
    selenium:
        image: selenium/standalone-chrome-debug
        ports:
            - 4444:4444
            - 5901:5900 #vnc server
    integration-tests:
        environment:
            SELENIUM_HOST: selenium
            SELENIUM_PORT: 4444
        volumes:
            - $PWD:/app
        build:
            context: .
            dockerfile: rspec.dockerfile
        entrypoint: rspec
        command: 
            - --pattern
            - /app/spec/integration/*_spec.rb
    unit-tests:
        environment:
            SELENIUM_HOST: selenium
            SELENIUM_PORT: 4444
        volumes:
            - $PWD:/app
        build:
            context: .
            dockerfile: rspec.dockerfile
        entrypoint: rspec
        command: 
            - --pattern
            - /app/spec/unit/*_spec.rb